//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LineWithBotFrameworkApplication2.Models.InternetAccount
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineActivate
    {
        public int ID { get; set; }
        public string LineToken { get; set; }
        public string Cardcode { get; set; }
    }
}
