//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LineWithBotFrameworkApplication2.Models.Fttx
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PLANBDATA
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string U_ProjectCode { get; set; }
        public string U_ProjectName { get; set; }
        public string U_Owner { get; set; }
        public string U_ProvinceCode { get; set; }
        public Nullable<System.DateTime> U_CreateDate { get; set; }
        public string U_CreateBy { get; set; }
        public string U_UserWeb { get; set; }
        public string U_SaleCode { get; set; }
        public string U_Status { get; set; }
        public Nullable<decimal> U_MinComPoint { get; set; }
        public Nullable<decimal> U_Incentive { get; set; }
        public string U_IncentiveUnit { get; set; }
        public string U_Address { get; set; }
        public string U_ProType { get; set; }
        public string U_District { get; set; }
        public string U_Amphur { get; set; }
        public string U_Province { get; set; }
        public string U_Zipcode { get; set; }
        public Nullable<decimal> U_Lat { get; set; }
        public Nullable<decimal> U_Lon { get; set; }
        public string U_Tel { get; set; }
        public string U_Picture { get; set; }
        public string U_BankName { get; set; }
        public string U_BankAccNo { get; set; }
        public string U_BankAccType { get; set; }
        public string U_BankAccName { get; set; }
        public string U_SPName { get; set; }
        public string U_SPPort { get; set; }
        public string U_DealerCondo { get; set; }
        public string U_ComOwnerType { get; set; }
        public Nullable<int> U_TotalUnit { get; set; }
        public string U_Node { get; set; }
        public string U_SPCode { get; set; }
        public string U_InvBilling { get; set; }
        public Nullable<int> U_ElectCharge { get; set; }
        public Nullable<int> U_RentYFee { get; set; }
        public Nullable<int> U_RentMFee { get; set; }
        public string U_TemplateID { get; set; }
        public string U_TaxID { get; set; }
        public string U_BillAddress { get; set; }
        public string U_BillDistrict { get; set; }
        public string U_BillAmphur { get; set; }
        public string U_BillProvince { get; set; }
        public string U_BillZipcode { get; set; }
        public string U_BillName { get; set; }
        public string U_ContractFileName { get; set; }
        public string U_PlanBType { get; set; }
        public string U_ContractNo { get; set; }
        public string U_PlanBInstallCode { get; set; }
        public Nullable<System.DateTime> U_ContractExp { get; set; }
        public string U_InvAttachment { get; set; }
        public string U_Remark { get; set; }
        public Nullable<int> U_DefaultPro { get; set; }
    }
}
