//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LineWithBotFrameworkApplication2.Models.Fttx
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SM_INAC
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public int DocEntry { get; set; }
        public string Canceled { get; set; }
        public string Object { get; set; }
        public Nullable<int> LogInst { get; set; }
        public Nullable<int> UserSign { get; set; }
        public string Transfered { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<short> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<short> UpdateTime { get; set; }
        public string DataSource { get; set; }
        public string U_BpCode { get; set; }
        public string U_BpName { get; set; }
        public string U_IDCode { get; set; }
        public string U_Address { get; set; }
        public string U_Tel { get; set; }
        public string U_Email { get; set; }
        public string U_Splitter { get; set; }
        public Nullable<int> U_Port { get; set; }
        public string U_Status { get; set; }
        public Nullable<System.DateTime> U_ContDate { get; set; }
        public Nullable<System.DateTime> U_InstDate { get; set; }
        public Nullable<int> U_AdvPd { get; set; }
        public Nullable<System.DateTime> U_BillDate { get; set; }
        public Nullable<System.DateTime> U_TermDate { get; set; }
        public string U_PckCode { get; set; }
        public string U_PckDtail { get; set; }
        public string U_Remark { get; set; }
        public Nullable<decimal> U_PckPrice { get; set; }
        public Nullable<int> U_BillDay { get; set; }
        public string U_Onu { get; set; }
        public string U_Sno { get; set; }
        public string U_MacA { get; set; }
        public string U_Usrcr { get; set; }
        public string U_TUser { get; set; }
        public string U_TPass { get; set; }
        public string U_Actby { get; set; }
        public string U_TotNo { get; set; }
        public string U_BillTo { get; set; }
        public string U_InsTo { get; set; }
        public string U_StmTo { get; set; }
        public string U_MSts { get; set; }
        public string U_Dbloss { get; set; }
        public string U_Prof { get; set; }
        public string U_DCode { get; set; }
        public string U_DName { get; set; }
        public string U_WStat { get; set; }
        public string U_WTxt { get; set; }
        public string U_BCode { get; set; }
        public string U_Reason { get; set; }
        public Nullable<System.DateTime> U_Next { get; set; }
        public Nullable<System.DateTime> U_DPDate { get; set; }
        public string U_DPRef { get; set; }
        public string U_DPlan { get; set; }
        public Nullable<short> U_PrePaid { get; set; }
        public string U_AdsType { get; set; }
        public string U_AdsOther { get; set; }
        public string U_ProID { get; set; }
        public string U_ProName { get; set; }
        public string U_PairAcc { get; set; }
        public string U_Email2 { get; set; }
        public Nullable<System.DateTime> U_TranfDate { get; set; }
        public string U_TranfTo { get; set; }
        public string U_Other { get; set; }
        public string U_Sno2 { get; set; }
        public string U_MacA2 { get; set; }
        public string U_BranchNo { get; set; }
        public string U_UsrWID { get; set; }
        public Nullable<System.DateTime> U_AptDate { get; set; }
        public Nullable<System.DateTime> U_SurveyDate { get; set; }
        public string U_Swatcat { get; set; }
        public Nullable<short> U_CtPeriod { get; set; }
        public string U_RWifi { get; set; }
        public string U_OldBpCode { get; set; }
        public string U_RecurCredit { get; set; }
        public string U_SaleName { get; set; }
        public Nullable<decimal> U_SaleCom { get; set; }
        public string U_Recurcardno { get; set; }
        public string U_RecurBank { get; set; }
        public string U_Recurbankno { get; set; }
        public string U_Recurbankname { get; set; }
        public string U_OSCode { get; set; }
        public string U_OSName { get; set; }
        public string U_SaleCode { get; set; }
        public Nullable<decimal> U_Oscom { get; set; }
        public Nullable<System.DateTime> U_FEDate { get; set; }
        public string U_FEStatus { get; set; }
        public string U_FERemark { get; set; }
        public Nullable<short> U_DevicePort { get; set; }
        public string U_DeviceMAC { get; set; }
        public string U_DeviceDetail { get; set; }
        public string U_DeviceName { get; set; }
        public string U_DeviceInsCode { get; set; }
        public string U_BuildingName { get; set; }
        public string U_PlanBCode { get; set; }
        public string U_WifiPassword { get; set; }
        public string U_VendorCode { get; set; }
        public string U_Billing { get; set; }
        public string U_LineID { get; set; }
        public Nullable<System.DateTime> U_StopPrintDate { get; set; }
        public string U_ActiveType { get; set; }
        public string U_Protocol { get; set; }
        public string U_RecurLinePay { get; set; }
        public string U_Index { get; set; }
        public string U_Vlan { get; set; }
        public string U_Language { get; set; }
        public string U_SymcVlan { get; set; }
        public string U_IPType { get; set; }
        public string U_Purpose { get; set; }
        public string U_Wrong { get; set; }
        public Nullable<int> U_LoginType { get; set; }
        public string U_Ip { get; set; }
        public string U_DunningCall { get; set; }
        public string U_PrimetimeCode { get; set; }
        public string U_Complimentary { get; set; }
        public Nullable<decimal> U_PercentSharing { get; set; }
    }
}
